#!/bin/bash

apt-get update -y
apt-get install nginx -y

nginx_conf="/etc/nginx/sites-available/default"

sed -i "/server_name _;/a \ \tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }" $nginx_conf

service nginx restart
