#!/usr/bin/env bash
# CMNT

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i "/server_name _;/a \ \tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }" /etc/nginx/sites-available/default

service nginx restart
