#!/usr/bin/env bash
# CMNT

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/error_404.html


sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

service nginx restart
