#!/usr/bin/env bash
# CMNT

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i "/server_name _;/a \    error_page 404 /error_404.html;" /etc/nginx/sites-available/default

service nginx restart
