#!/bin/bash

# check if listen 80 default_server; is present in the default server block of Nginx configuration file
if ! grep -q "listen 80 default_server;" /etc/nginx/sites-enabled/default; then
    awk '/^server {/,/^listen \[::\]:80 default_server;/ { if ($0 ~ /^ *listen [[:digit:]]+ default_server;/) print "        listen 80 default_server;"; else print; next } 1' /etc/nginx/sites-enabled/default > /tmp/default.tmp && sudo mv /tmp/default.tmp /etc/nginx/sites-enabled/default
fi

# Check if another web server is running on port 80
if sudo netstat -tuln | grep -q ":80"; then
    sudo systemctl stop apache2
fi

# Check if Nginx is run with sudo privileges
if ! sudo nginx -t -c /etc/nginx/nginx.conf &> /dev/null; then
    sudo systemctl restart nginx
fi

# Check if UFw firewall is blocking Nginx from binding to port 80
if sudo ufw status | grep -q "80/tcp"; then
    sudo ufw allow 80/tcp
fi
